#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#la route qui va permettre à LexikJWT d'intercepter la requète pour pouvoir se connecterq 
api_login_check:
    path: /api/login_check
